apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-aws-iam-controller
  name: kube-aws-iam-controller
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - pods
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
      - extensions
    resources:
      - secrets
    verbs:
      - list
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-aws-iam-controller
  name: kube-aws-iam-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-aws-iam-controller
subjects:
  - kind: ServiceAccount
    name: kube-aws-iam-controller
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-aws-iam-controller
  name: kube-aws-iam-controller
  namespace: kube-system
