apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
  namespace: logging
  labels:
    app: aggregator
data:
  fluent.conf: |
    <source>
      type forward
      bind 0.0.0.0
      port 24224
    </source>

    <match **>
      type stdout
    </match>
