apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: logging
spec:
  ports:
    - port: 24224
      targetPort: 24224
      protocol: TCP
  type: ClusterIP
  selector:
    app: aggregator
